language: python

python:
    - 2.5
    - 2.6
    - 2.7

branches:
    only:
        - master
        - develop

install:
    - pip install nose

script:
    - make travis

env: TESTER_URL=http://h.wrttn.me/
